"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const classData_1 = require("./classData");
const StudentDisplay_1 = require("./StudentDisplay");
const TeacherDisplay_1 = require("./TeacherDisplay");
const classdata = new classData_1.ClassData();
const s1 = new StudentDisplay_1.StudentDisplay();
classdata.registerObserver(s1);
console.log("1st output");
classdata.measuredChanged("SWE-4501", "10/07/2021, 4:36 PM", "Observer Pattern", "ABC");
const s2 = new StudentDisplay_1.StudentDisplay();
classdata.registerObserver(s2);
console.log("\n\n\n2nd output");
classdata.measuredChanged("SWE-4501", "10.07.2021, 23:55", "Observer Pattern", "ABC");
classdata.removeObserver(s2);
console.log("\n\n\n3rd output");
classdata.measuredChanged("SWE-4501", "10.07.2021, 23:56", "Observer Pattern", "ABC");
const t1 = new TeacherDisplay_1.TeacherDisplay();
classdata.registerObserver(t1);
console.log("\n\n\n4th output");
classdata.measuredChanged("SWE-4501", "10.07.2021, 23:57", "Observer Pattern", "ABC");
