name: gh-pages
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: deploy to gh pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Set Node.js 24.x
        uses: actions/setup-node@v3
        with:
          node-version: 24.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm predeploy
        env:
          PUBLIC_URL: "https://mmncit.github.io/dpatterna"

      - name: Build and deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: public