name: CI
on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Set Node.js 24.x
        uses: actions/setup-node@v3
        with:
          node-version: 24.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Test the app
        run: pnpm test
